# Generated by Django 4.0.6 on 2022-08-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='available_seats',
            field=models.IntegerField(default=60),
        ),
    ]
