# Generated by Django 4.0.6 on 2022-08-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_alter_seat_seat_booked_time_alter_seat_seta_book_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
