# Generated by Django 4.0.6 on 2022-08-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_remove_seat_seat_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seat',
            field=models.ManyToManyField(blank=True, null=True, to='buses.seat_details'),
        ),
    ]
