# Generated by Django 4.0.6 on 2022-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0007_alter_bus_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat_details',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
